live_config_reload = true

[window]
opacity = 0.85
padding = { x = 18, y = 16 }
dynamic_padding = false
decorations = "Buttonless"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 22

[scrolling]
history = 10000
